FROM golang:1.25.5-alpine AS builder



WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o risk-feature-api ./cmd/api

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/risk-feature-api .

CMD ["./risk-feature-api"]