apiVersion: v1
kind: Secret
metadata:
  name: pipeline-secret
  namespace: risk-pipeline
type: Opaque
stringData:
  KAFKA_SASL_USERNAME: ""
  KAFKA_SASL_PASSWORD: ""
  TIDB_PASSWORD: ""
  PG_PASSWORD: ""